--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/BankNotesPlus
build-by-default: true
branches:
- main
projects:
  BankNotesPlus:
    path: ""
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
...
