name: BankNotesPlus
version: 1.0.0
author: Terpz710
api: 5.0.0
main: terpz710\banknotesplus\BankNotesPlus

softdepend: ["EconomyAPI", "BedrockEconomy"]

permissions:
  banknotesplus.cmd:
    default: true
