name: BankNotesPlus
version: 1.0.5
author: Terpz710
api: 5.3.0
main: terpz710\banknotesplus\BankNotesPlus

softdepend: ["EconomyAPI", "BedrockEconomy"]

permissions:
  banknotesplus.cmd:
    default: true
