name: BankNotesPlus
version: 1.0.1
api: [5.0.0]
main: Terpz710\BankNotesPlus\BankNotesPlus
author: Terpz710
description: Allows the creation of bank notes using muli-ecomony system.

permissions:
  banknotesplus.cmd:
    description: Bank Note Perm
    default: true
