name: BankNotesPlus
version: 1.0.0
api: [5.0.0]
main: Terpz710\BankNotesPlus\BankNotesPlus
author: Terpz710

softdepend: ["EconomyAPI", "BedrockEconomy"]

permissions:
  banknotesplus.cmd:
    default: true
